module.exports = (sequelize, DataTypes) => sequelize.define('SocialAccount', {
  id: { type: DataTypes.INTEGER.UNSIGNED, autoIncrement: true, primaryKey: true },
  platform: {
    type: DataTypes.ENUM('facebook', 'instagram', 'twitter', 'linkedin', 'tiktok', 'youtube'),
    allowNull: false,
    unique: true,
  },
  is_connected: { type: DataTypes.BOOLEAN, defaultValue: false },
  display_name: { type: DataTypes.STRING },
  page_id: { type: DataTypes.STRING },
  page_access_token: { type: DataTypes.TEXT },
  instagram_account_id: { type: DataTypes.STRING },
  twitter_api_key: { type: DataTypes.STRING },
  twitter_api_secret: { type: DataTypes.STRING },
  twitter_access_token: { type: DataTypes.STRING },
  twitter_access_secret: { type: DataTypes.STRING },
  linkedin_access_token: { type: DataTypes.TEXT },
  linkedin_org_id: { type: DataTypes.STRING },
  tiktok_access_token: { type: DataTypes.TEXT },
  tiktok_open_id: { type: DataTypes.STRING },
  youtube_access_token: { type: DataTypes.TEXT },
  youtube_refresh_token: { type: DataTypes.TEXT },
  youtube_channel_id: { type: DataTypes.STRING },
  last_publish_at: { type: DataTypes.DATE },
  last_publish_error: { type: DataTypes.TEXT },
}, { tableName: 'social_accounts' });
